### ISSUE TITLE
Hide credentials in `docker-compose.yml`

### ISSUE THREAD

**Issue by zhaojj2209** [zhaojj2209/teammates#14]
Credentials (e.g. username, password) should be hidden from any files that will be publicly visible in a commit. We can hide these credentials in environment variables.

Useful links:
* https://docs.docker.com/compose/environment-variables/
* https://blog.alec.coffee/running-sql-migrations-before-booting-docker-compose-services

**Comment by jianhandev** [comment]
Closing this since we only use docker in dev, the password thus need not be secret. CloudSQL probably provides its own way of managing DB passworda.

https://cloud.google.com/sql/docs/postgres/users

**Comment by jianhandev** [comment]
Closing this since we only use docker in dev, the password thus need not be secret. CloudSQL probably provides its own way of managing DB passworda.

https://cloud.google.com/sql/docs/postgres/users
