### ISSUE TITLE
Explore how to set up base test case with local SQL DB access

### ISSUE THREAD

**Issue by zhaojj2209** [zhaojj2209/teammates#18]
Explore how to write component tests (e.g. for course) against SQL DB. Run tests for CoursesDb, CoursesLogic, and a few course-only APIs.

**Updated:**
The current most viable solution is to use throwaway instances of databases running in Docker containers.

There are two options we can consider:
* Option A: [OpenTable Embedded PostgreSQL Component](https://github.com/opentable/otj-pg-embedded)
  * This library is maintained by OpenTable, Inc. It uses TestContainers under the hood, but adds value with builders, the api compatibility, the wrapping around Flyway to allow users to adopt a smooth transition to a Docker-based test approach.
* Option B: [TestContainers](https://www.testcontainers.org/)
  * We can also directly use TestContainers, a well-known Java library that supports JUnit tests, providing lightweight, throwaway instances of common databases
  * We will need to integrate Flyway with TestContainers ourselves

**Comment by jianhandev** [comment]
Currently focusing on issue #16, if anyone has time to explore this feel free to reassign this to yourself.

**Comment by hhdqirui** [comment]
An alternative is to use an embedded PostgreSQL database for unit testing.  
Pros: It seems that it is relatively easier to set up the entire testing framework. It can be installed and managed by Gradle. It can used to write JUnit tests.
Cons: This library seems to be less well-known. Moreover, since it is not a real PostrgreSQL instance, the behaviour might be different from a real PostgreSQL instance.
https://github.com/opentable/otj-pg-embedded  
https://github.com/zonkyio/embedded-postgres

**Comment by jianhandev** [comment]
> An alternative is to use an embedded PostgreSQL database for unit testing.

Thanks for suggesting the alternatives. Let's consolidate out findings in this google doc, I did some quick research there could be many approaches to this.

https://docs.google.com/document/d/1OATm_5TuzpFQPJ6uor2J4MbHRL5-Zg9hCV3rnbcCm3I/edit

**Comment by jianhandev** [comment]
> There are two options we can consider:
> 
> * Option A: [OpenTable Embedded PostgreSQL Component](https://github.com/opentable/otj-pg-embedded)
>   
>   * This library is maintained by OpenTable, Inc. It uses TestContainers under the hood, but adds value with builders, the api compatibility, the wrapping around Flyway to allow users to adopt a smooth transition to a Docker-based test approach.
> * Option B: [TestContainers](https://www.testcontainers.org/)
>   
>   * We can also directly use TestContainers, a well-known Java library that supports JUnit tests, providing lightweight, throwaway instances of common databases
>   * We will need to integrate Flyway with TestContainers ourselves

@hhdqirui would you like to work on this? I think either option might work for us, OpenTable Embedded PostgreSQL Component would be easier to get started with. We also need to explore how to integrate it successfully in our CI/CD pipeline.
