### ISSUE TITLE
Implement a routine involving join operations

### ISSUE THREAD

**Issue by zhaojj2209** [zhaojj2209/teammates#19]
Demonstrate how a join operation between two tables would work, e.g. `getCoursesForInstructors` (should return a list of courses, except for courses in the recycle bin, for a given list of instructors)

**Comment by jianhandev** [comment]
@hhdqirui @samuelfangjw @NicolasCwy would any of you like to work on this?

**Comment by jianhandev** [comment]
@samuelfangjw are you still working on this?
