### ISSUE TITLE
Handle exceptions thrown by Hibernate

### ISSUE THREAD

**Issue by zhaojj2209** [zhaojj2209/teammates#20]
Many conditions can cause exceptions to be thrown while using Hibernate. These can be mapping errors, infrastructure problems, SQL errors, data integrity violations, session problems, and transaction errors.

These exceptions mostly extend from [HibernateException](https://docs.jboss.org/hibernate/orm/6.0/javadocs/org/hibernate/HibernateException.html). 

Furthermore, most of these are unrecoverable. As a result, retrying the operation would not help. This means we have to abandon the current session on encountering them.

Useful links:
* https://www.baeldung.com/hibernate-exceptions

**Comment by jianhandev** [comment]
@hhdqirui @samuelfangjw @NicolasCwy would any of you like to work on this?

**Comment by NicolasCwy** [comment]
The rest seem to require more DB knowledge and I don't want to slow the pace down for the project. Will be taking a look at this
