### ISSUE TITLE
Explore how indexing works in Hibernate

### ISSUE THREAD

**Issue by zhaojj2209** [zhaojj2209/teammates#21]
Explore how to define indexes on columns of a table.

**Comment by jianhandev** [comment]
@hhdqirui @samuelfangjw @NicolasCwy would any of you like to work on this?

**Comment by jianhandev** [comment]
@samuelfangjw are you still working on this?

**Comment by samuelfangjw** [comment]
Hi it is unlikely I will have time until next month, feel free to take it.

**Comment by jianhandev** [comment]
@zhaojj2209 @ziqing26 @hhdqirui anyone of you would like to take this up?
