### ISSUE TITLE
Transaction methods should not be called in the DB layer

### ISSUE THREAD

**Issue by samuelfangjw** [zhaojj2209/teammates#25]
How to group transactions is business logic and ideally should not be defined in the db layer.

A simple way to rationalise this, say we need to apply a transaction that does operation A on courses then operation B on instructors. If the transaction is to be defined in the db layer, we need to write this specific method in db layer.

```
Transaction tx = ...
operationAOnCourses()
operationBOnInstructors()
tx.commit()
```

As you can see, we are now forced to move the business logic to the db layer.

**Comment by jianhandev** [comment]
> How to group transactions is business logic and ideally should not be defined in the db layer.

@samuelfangjw do you want to create a PR to refactor that?
